Update bertram.py
Fix the error in the add_word_vectors_to_model function.
runtimeerror: a view of a leaf variable that requires grad is being used in an in-place operation.
--> with torch.no_grad():